services:
  recruitment-db:
    image: mysql:8.0
    restart: always
    env_file:
      # - .env
      - preprod.env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    volumes:
      - recruitment_db:/var/lib/mysql
      - ./init-db-permission.sh:/docker-entrypoint-initdb.d/init-db-permission.sh
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  recruitment-backend:
    build:
      context: .
      # target: development
      target: production
    restart: always
    depends_on:
      recruitment-db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
volumes:
  recruitment_db:
